/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AgendaGUI;

import AgendaContacte.Enums.CriteriuOrdonare;
import AgendaContacte.ExtensionMethods.AgendaValidation;
import AgendaContacte.ExceptionClasses.NumePersoanaException;
import AgendaContacte.Models.Contact;
import AgendaContacte.Models.NrFix;
import AgendaContacte.Models.NrMobil;
import AgendaContacte.Models.NrTel;
import AgendaContacte.Models.Persoana;
import java.awt.Toolkit;
import java.time.LocalDate;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author AndreiR
 */
public class AdaugaContactGUI extends javax.swing.JFrame {

    Persoana persoana;
    NrTel telefonPersoana;
    Contact contactNou;
    AgendaGUI agendaPrimara;

    public Contact getContactNou() {
        return contactNou;
    }

    /**
     * Creates new form AdaugaContactGUI
     */
    public AdaugaContactGUI(AgendaGUI agenda) {
        initComponents();
        setIcon();
        setGroupRadioButton();
        agendaPrimara = agenda;
    }

    public AdaugaContactGUI() {
        initComponents();
        setIcon();
        setGroupRadioButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        numeJLabel = new javax.swing.JLabel();
        prenumeJLabel = new javax.swing.JLabel();
        dataNasteriiJLabel = new javax.swing.JLabel();
        tipNumarJLabel = new javax.swing.JLabel();
        numeJTextField = new javax.swing.JTextField();
        prenumeJTextField = new javax.swing.JTextField();
        ziJTextField = new javax.swing.JTextField();
        ziJLabel = new javax.swing.JLabel();
        lunaJTextField = new javax.swing.JTextField();
        lunaJLabel = new javax.swing.JLabel();
        anJTextField = new javax.swing.JTextField();
        anJLabel = new javax.swing.JLabel();
        nrMobilJRadioButton = new javax.swing.JRadioButton();
        nrFixJRadioButton = new javax.swing.JRadioButton();
        adaugaContactJButton = new javax.swing.JButton();
        renuntaJButton = new javax.swing.JButton();
        numarTelefonJLabel = new javax.swing.JLabel();
        numarTelJTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adauga Contact");

        numeJLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        numeJLabel.setText("Nume:");

        prenumeJLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        prenumeJLabel.setText("Prenume:");

        dataNasteriiJLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        dataNasteriiJLabel.setText("Data nasterii:");

        tipNumarJLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tipNumarJLabel.setText("Tip numar:");

        numeJTextField.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        prenumeJTextField.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        ziJTextField.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        ziJLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        ziJLabel.setText("Zi:");

        lunaJTextField.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        lunaJLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lunaJLabel.setText("Luna:");

        anJTextField.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        anJLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        anJLabel.setText("An:");

        nrMobilJRadioButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        nrMobilJRadioButton.setText("Numar mobil");

        nrFixJRadioButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        nrFixJRadioButton.setText("Numar Fix");

        adaugaContactJButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        adaugaContactJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AgendaGUI/icoImages/add-button-inside-black-circle_icon.png"))); // NOI18N
        adaugaContactJButton.setText("Adauga contact");
        adaugaContactJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaugaContactJButtonActionPerformed(evt);
            }
        });

        renuntaJButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        renuntaJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AgendaGUI/icoImages/cancel_button_black.png"))); // NOI18N
        renuntaJButton.setText("Renunta");
        renuntaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renuntaJButtonActionPerformed(evt);
            }
        });

        numarTelefonJLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        numarTelefonJLabel.setText("Numar telefon: ");

        numarTelJTextField.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adaugaContactJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addGap(37, 37, 37)
                        .addComponent(renuntaJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numarTelefonJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numarTelJTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeJLabel)
                            .addComponent(prenumeJLabel)
                            .addComponent(dataNasteriiJLabel)
                            .addComponent(tipNumarJLabel))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nrFixJRadioButton)
                                .addGap(28, 28, 28)
                                .addComponent(nrMobilJRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(prenumeJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ziJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ziJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lunaJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(lunaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(anJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anJTextField))
                            .addComponent(numeJTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeJLabel)
                    .addComponent(numeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenumeJLabel)
                    .addComponent(prenumeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lunaJLabel)
                    .addComponent(anJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anJLabel)
                    .addComponent(dataNasteriiJLabel)
                    .addComponent(ziJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ziJLabel)
                    .addComponent(lunaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipNumarJLabel)
                    .addComponent(nrMobilJRadioButton)
                    .addComponent(nrFixJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numarTelefonJLabel)
                    .addComponent(numarTelJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adaugaContactJButton)
                    .addComponent(renuntaJButton))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adaugaContactJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaugaContactJButtonActionPerformed

        boolean isPersonValid = verificarePersoana();
        String numarTel = this.numarTelJTextField.getText();

        if (isPersonValid) {
            if (nrFixJRadioButton.isSelected()) {
                telefonPersoana = new NrFix(numarTel);
            } else if (nrMobilJRadioButton.isSelected()) {
                telefonPersoana = new NrMobil(numarTel);
            } else {
                JOptionPane.showMessageDialog(this, "Va rugam sa bifati tipul numarului de telefon",
                        "Setare numar telefon.", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (telefonPersoana.getNrTel().equals("N/A")) {
                JOptionPane.showMessageDialog(this, "Numarul de telefon nu se afla in formatul corect sau nu respecta tipul bifat (mobil/fix).\nAti introdus: " + numarTel + "\nMai incercati...",
                        "Setare numar telefon.", JOptionPane.INFORMATION_MESSAGE);
            } else {
                contactNou = new Contact(persoana, telefonPersoana);

                if (!verificareDuplicat()) {
                    agendaPrimara.agenda.adaugaContact(contactNou);

                    //si dupa revenim la agenda initiala prin apelarea ei. - TODO: nu prea imi place ca pot sa accesez in paralel si form-ul din urma,.. sa verific cum il blochez cat timp sunt in asta.
                    agendaPrimara.updateAgendaModel();
                    urareLMA();
                    JOptionPane.showMessageDialog(this, "Contactul creat a fost adaugat in lista",
                            "Contact adaugat!", JOptionPane.INFORMATION_MESSAGE);

                    this.setVisible(false);

                } else {
                    JOptionPane.showMessageDialog(this, "Contactul exista deja in agenda!\nMai incercati.",
                            "Contact existent!", JOptionPane.ERROR_MESSAGE);
                    this.setVisible(false);
                }
            }

        }
    }//GEN-LAST:event_adaugaContactJButtonActionPerformed

    private void renuntaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renuntaJButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_renuntaJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Metal (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdaugaContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdaugaContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdaugaContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdaugaContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdaugaContactGUI().setVisible(true);
            }
        });
    }

    private void setIcon() {
        String iconPath = "C:\\Andrei stuff\\Curs Java InfoAcademy\\Proiect Final Java Andrei R\\ProiectFinalJavaAR\\src\\AgendaGUI\\icoImages\\user-black-close-up-shape_icon.png";
        setIconImage(Toolkit.getDefaultToolkit().getImage(iconPath));
    }

    private void setGroupRadioButton() {
        buttonGroup1 = new ButtonGroup();
        buttonGroup1.add(nrFixJRadioButton);
        buttonGroup1.add(nrMobilJRadioButton);
    }

    private boolean verificarePersoana() {

        String nume = this.numeJTextField.getText();
        String prenume = this.prenumeJTextField.getText();
        boolean isValid;

        //validam numele  de familie
        if (AgendaValidation.validareNume(nume)) {
            //acum validam prenumele
            if (AgendaValidation.validareNume(prenume)) {

                int an = 0;
                int luna = 0;
                int zi = 0;

                try {
                    an = Integer.parseInt(this.anJTextField.getText());
                    luna = Integer.parseInt(this.lunaJTextField.getText());
                    zi = Integer.parseInt(this.ziJTextField.getText());
                } catch (java.lang.NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Data de nastere invalida"
                            + "\nInfo: " + ex.getMessage(), "Data nastere invalida.", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
                //acum validam data de nastere
                if (AgendaValidation.isDateValid(an, luna, zi)) {
                    LocalDate dataNasterii = LocalDate.of(an, luna, zi);
                    try {
                        //daca totul este inregula, setam datele persoanei
                        persoana = new Persoana(nume, prenume, dataNasterii);
                        isValid = true;

                    } catch (NumePersoanaException ex) {
                        JOptionPane.showMessageDialog(this, "Contactul nu a putut fi setat"
                                + "\nInfo: " + ex.getMessage(), "Eroare.", JOptionPane.ERROR_MESSAGE);
                        isValid = false;
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Data de nastere nu este valida"
                            + "\nMai incercati...", "Data nastere invalida.", JOptionPane.INFORMATION_MESSAGE);
                    isValid = false;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Prenumele nu este valid"
                        + "\nMai incercati...", "Prenume invalid", JOptionPane.INFORMATION_MESSAGE);
                isValid = false;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Numele de familie nu este valid"
                    + "\nMai incercati...", "Nume familie invalid", JOptionPane.INFORMATION_MESSAGE);
            isValid = false;
        }

        return isValid;
    }

    private boolean verificareDuplicat() {

        String nume = this.numeJTextField.getText();
        String prenume = this.prenumeJTextField.getText();
        String telefon = this.numarTelJTextField.getText();

        boolean isDuplicate = false;

        for (Contact contact : this.agendaPrimara.contacte) {
            if (nume.equals(contact.getContactPersoana().getNume())
                    && prenume.equals(contact.getContactPersoana().getPrenume())) {
                isDuplicate = true;
                break;
            } else {
                if (telefon.equals(contact.getNumarTelefon().getNrTel())) {
                    isDuplicate = true;
                    break;
                } else {
                    isDuplicate = false;
                }
            }
        }
        return isDuplicate;
    }

    //verificam daca la adaugare este ziua de nastere a contactului si afisam un mesaj daca este ziua lui
    private void urareLMA() {
        if (Integer.parseInt(this.ziJTextField.getText()) == LocalDate.now().getDayOfMonth()
                && Integer.parseInt(this.lunaJTextField.getText()) == LocalDate.now().getMonthValue()) {
            JOptionPane.showMessageDialog(this, "Astazi este ziua lui " + contactNou.getContactPersoana().getFullName(CriteriuOrdonare.DUPA_NUME)
                    + "\nUreaza-i la multi ani :)",
                    "La multi ani!", JOptionPane.INFORMATION_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adaugaContactJButton;
    private javax.swing.JLabel anJLabel;
    private javax.swing.JTextField anJTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dataNasteriiJLabel;
    private javax.swing.JLabel lunaJLabel;
    private javax.swing.JTextField lunaJTextField;
    private javax.swing.JRadioButton nrFixJRadioButton;
    private javax.swing.JRadioButton nrMobilJRadioButton;
    private javax.swing.JTextField numarTelJTextField;
    private javax.swing.JLabel numarTelefonJLabel;
    private javax.swing.JLabel numeJLabel;
    private javax.swing.JTextField numeJTextField;
    private javax.swing.JLabel prenumeJLabel;
    private javax.swing.JTextField prenumeJTextField;
    private javax.swing.JButton renuntaJButton;
    private javax.swing.JLabel tipNumarJLabel;
    private javax.swing.JLabel ziJLabel;
    private javax.swing.JTextField ziJTextField;
    // End of variables declaration//GEN-END:variables

}
